4 database designmodel
NokulungaM/DataForgeAI-Capstone-FullStack pull request #61
Opened 2024-09-27 10:12 UTC by ImisebenziEmihle

I updated the models file with the ratings schema as requested.

2024-09-27 11:06 UTC, Nhlanhla-advocate requested changes
There are conflicts that need to be fixed before merging. Please fix the conflicts then push the code again. If you need any assistance, shout to the team.

2024-09-27 14:44 UTC, ImisebenziEmihle commented
@Nhlanhla-advocate @mpilomthiyane97 Please review the recent commits and approve PR.

2024-09-30 08:01 UTC, mpilomthiyane97 approved these changes

2024-09-30 11:45 UTC, Nhlanhla-advocate commented
Just reviewed your code, it's ready to merge

2024-09-30 11:45 UTC, closed without merging